controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
grid:
    path:       /grid/display
    controller: App\Controller\GridDisplayController::index